/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpr.ads.extendslcc.academia.view.turma;

import br.edu.ifpr.ads.extendslcc.academia.bean.Atividade;
import br.edu.ifpr.ads.extendslcc.academia.bean.Instrutor;
import br.edu.ifpr.ads.extendslcc.academia.bean.Turma;
import br.edu.ifpr.ads.extendslcc.academia.dao.AtividadeDao;
import br.edu.ifpr.ads.extendslcc.academia.dao.InstrutorDao;
import br.edu.ifpr.ads.extendslcc.academia.dao.TurmaDao;
import br.edu.ifpr.ads.extendslcc.academia.util.ConnectionFactory;
import br.edu.ifpr.ads.extendslcc.academia.view.component.FilterListModel;
import br.edu.ifpr.ads.extendslcc.academia.view.component.GenericComboModel;
import br.edu.ifpr.ads.extendslcc.academia.view.component.GenericTypeList;
import java.awt.Component;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.function.Function;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author aluno
 */
public class ViewTurma extends javax.swing.JFrame{

    /**
     * Creates new form WindowProprietario
     */
    public ViewTurma(){
        initComponents();

        onInit();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        paneTitledContainer = new javax.swing.JPanel();
        paneBorderLayout = new javax.swing.JPanel();
        paneLeft = new javax.swing.JPanel();
        paneList = new javax.swing.JPanel();
        tfSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listElements = new javax.swing.JList<>();
        lblSearch = new javax.swing.JLabel();
        PaneRight = new javax.swing.JPanel();
        paneFields = new javax.swing.JPanel();
        dataFim = new datechooser.beans.DateChooserCombo();
        lblNascimento = new javax.swing.JLabel();
        dataInicio = new datechooser.beans.DateChooserCombo();
        lblNascimento1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbInstrutor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbAtividade = new javax.swing.JComboBox<>();
        timeHorario = new com.github.lgooddatepicker.components.TimePicker();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnControleAtividade = new javax.swing.JButton();
        timeDuracao = new com.github.lgooddatepicker.components.TimePicker();
        paneControls = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Proprietário");

        paneTitledContainer.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Controle de Turma", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N

        paneBorderLayout.setLayout(new java.awt.BorderLayout());

        paneLeft.setPreferredSize(new java.awt.Dimension(455, 367));

        paneList.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Lista de Turma", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jScrollPane1.setViewportView(listElements);

        lblSearch.setText("Pesquisar:");

        javax.swing.GroupLayout paneListLayout = new javax.swing.GroupLayout(paneList);
        paneList.setLayout(paneListLayout);
        paneListLayout.setHorizontalGroup(
            paneListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(paneListLayout.createSequentialGroup()
                        .addComponent(lblSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneListLayout.setVerticalGroup(
            paneListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneListLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(paneListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout paneLeftLayout = new javax.swing.GroupLayout(paneLeft);
        paneLeft.setLayout(paneLeftLayout);
        paneLeftLayout.setHorizontalGroup(
            paneLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneLeftLayout.createSequentialGroup()
                .addComponent(paneList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneLeftLayout.setVerticalGroup(
            paneLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLeftLayout.createSequentialGroup()
                .addComponent(paneList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        paneBorderLayout.add(paneLeft, java.awt.BorderLayout.CENTER);

        PaneRight.setPreferredSize(new java.awt.Dimension(600, 367));

        paneFields.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Turma", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        lblNascimento.setText("Data de Fim:");

        lblNascimento1.setText("Data de Inicio:");

        jLabel1.setText("Instrutor:");

        jLabel2.setText("Atividade:");

        jLabel3.setText("Horário:");

        jLabel4.setText("Duração:");

        btnControleAtividade.setText("...");
        btnControleAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControleAtividadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneFieldsLayout = new javax.swing.GroupLayout(paneFields);
        paneFields.setLayout(paneFieldsLayout);
        paneFieldsLayout.setHorizontalGroup(
            paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneFieldsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lblNascimento1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbInstrutor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(paneFieldsLayout.createSequentialGroup()
                        .addComponent(cbAtividade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnControleAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneFieldsLayout.createSequentialGroup()
                        .addComponent(dataInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneFieldsLayout.createSequentialGroup()
                        .addComponent(timeHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timeDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneFieldsLayout.setVerticalGroup(
            paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneFieldsLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnControleAtividade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(timeDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneFieldsLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblNascimento))
                    .addComponent(dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNascimento1))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PaneRightLayout = new javax.swing.GroupLayout(PaneRight);
        PaneRight.setLayout(PaneRightLayout);
        PaneRightLayout.setHorizontalGroup(
            PaneRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PaneRightLayout.setVerticalGroup(
            PaneRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneRightLayout.createSequentialGroup()
                .addComponent(paneFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        paneBorderLayout.add(PaneRight, java.awt.BorderLayout.LINE_END);

        paneControls.setPreferredSize(new java.awt.Dimension(948, 45));

        btnNew.setText("Cadastrar");
        btnNew.setPreferredSize(new java.awt.Dimension(90, 35));
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        paneControls.add(btnNew);

        btnUpdate.setText("Alterar");
        btnUpdate.setPreferredSize(new java.awt.Dimension(90, 35));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        paneControls.add(btnUpdate);

        btnDelete.setText("Excluir");
        btnDelete.setPreferredSize(new java.awt.Dimension(90, 35));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        paneControls.add(btnDelete);

        btnCancel.setText("Cancelar");
        btnCancel.setPreferredSize(new java.awt.Dimension(90, 35));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        paneControls.add(btnCancel);

        paneBorderLayout.add(paneControls, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout paneTitledContainerLayout = new javax.swing.GroupLayout(paneTitledContainer);
        paneTitledContainer.setLayout(paneTitledContainerLayout);
        paneTitledContainerLayout.setHorizontalGroup(
            paneTitledContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTitledContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBorderLayout, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneTitledContainerLayout.setVerticalGroup(
            paneTitledContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTitledContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBorderLayout, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneTitledContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneTitledContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private GenericComboModel<Atividade> comboModelAtividade;
    private GenericComboModel<Instrutor> comboModelInstrutor;
    private FilterListModel<Turma> listElemetsModel;
    private Turma currentTurma;

    private void onInit(){

        enableComponents( false );
        Connection con;

        try{

            con = ConnectionFactory.createConnectionToMySQL();
            TurmaDao turmaDao = new TurmaDao( con );
            listElemetsModel = new FilterListModel<Turma>( turmaDao.findAll() );
            listElements.setModel( listElemetsModel );
            con.close();

        }catch( SQLException ex ){

            System.out.println( "Erro na conexão do list Turma " + ex.getMessage() );

        }

        comboModelAtividade = new GenericComboModel<>();
        cbAtividade.setModel( comboModelAtividade );
        comboModelInstrutor = new GenericComboModel<>();
        cbInstrutor.setModel( comboModelInstrutor );

        updateComboAtividade();
        updateComboInstrutor();

        tfSearch.getDocument().addDocumentListener( new DocumentListener(){
            @Override
            public void insertUpdate( DocumentEvent e ){
                filter();
            }

            @Override
            public void removeUpdate( DocumentEvent e ){
                filter();
            }

            @Override
            public void changedUpdate( DocumentEvent e ){
                filter();
            }

            private void filter(){

                listElemetsModel.filter( tfSearch.getText() );

            }

        } );

        listElements.getSelectionModel().addListSelectionListener( new ListSelectionListener(){//seleção alterada

            @Override
            public void valueChanged( ListSelectionEvent e ){

                if( !e.getValueIsAdjusting() ){

                    if( listElements.getSelectedIndex() >= 0 ){

                        ViewTurma.this.currentTurma = listElements.getSelectedValue();
                        fillFieldsByTurma( ViewTurma.this.currentTurma );
                        btnUpdate.setEnabled( true );
                        btnDelete.setEnabled( true );

                    }else{

                        enableComponents( false );
                        btnUpdate.setEnabled( false );
                        btnDelete.setEnabled( false );

                    }

                }

            }

        } );

    }

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed

        this.emptyFields();
        this.currentTurma = new Turma();
        listElements.clearSelection();
        listElements.setEnabled( false );
        btnNew.setEnabled( false );
        btnDelete.setEnabled( false );
        btnCancel.setEnabled( true );
        btnUpdate.setEnabled( true );
        btnUpdate.setText( "Salvar" );
        enableComponents( true );

    }//GEN-LAST:event_btnNewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        if( btnNew.isEnabled() ){

            System.out.println( "Editar" );
            listElements.setEnabled( false );
            btnDelete.setEnabled( false );
            btnNew.setEnabled( false );
            btnUpdate.setText( "Salvar" );
            btnCancel.setEnabled( true );
            enableComponents( true );
            btnUpdate.setEnabled( true );

        }else{// EXECUTE SALVAR

            if( cbInstrutor.getSelectedIndex() == -1 || cbAtividade.getSelectedIndex() == -1 ){

                JOptionPane.showMessageDialog( this, "Selecione a atividade o instrutor", "Erro", JOptionPane.ERROR_MESSAGE );
                return;

            }

            if( timeHorario.getTime() == null ){

                JOptionPane.showMessageDialog( this, "Selecione o horário", "Erro", JOptionPane.ERROR_MESSAGE );
                return;

            }

            if( timeDuracao.getTime() == null ){

                JOptionPane.showMessageDialog( this, "Selecione a duração", "Erro", JOptionPane.ERROR_MESSAGE );
                return;

            }

            System.out.println( "Salvar" );
            listElements.setEnabled( true );
            btnNew.setEnabled( true );
            btnUpdate.setText( "Editar" );
            btnCancel.setEnabled( false );
            enableComponents( false );
            this.setTurmaByForms( this.currentTurma );

            if( !listElemetsModel.contains( currentTurma ) ){

                listElemetsModel.addElement( currentTurma );

            }

            listElements.setSelectedValue( this.currentTurma, true );

        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        Turma turma = listElements.getSelectedValue();
        listElements.clearSelection();
        listElemetsModel.removeElement( turma );
        btnDelete.setEnabled( false );
        turmaDaoOperate( ( dao ) -> dao.delete( turma ) );

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        listElements.setEnabled( true );
        btnNew.setEnabled( true );
        btnUpdate.setText( "Editar" );
        btnCancel.setEnabled( false );
        btnDelete.setEnabled( listElements.getSelectedValue() != null );
        enableComponents( false );

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnControleAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControleAtividadeActionPerformed

        try{

            Connection con = ConnectionFactory.createConnectionToMySQL();
            GenericTypeList< Atividade, AtividadeDao> titulacaoList = new GenericTypeList<>( "Atividade", Atividade::new, () -> new AtividadeDao( con ) );

            titulacaoList.setModal( true );
            titulacaoList.setLocationRelativeTo( this );
            titulacaoList.setVisible( true );
            updateComboAtividade();

        }catch( SQLException ex ){

            System.out.println( "Erro Na gerencia de Atividade" );
            ex.printStackTrace();

        }

    }//GEN-LAST:event_btnControleAtividadeActionPerformed

    private void updateComboAtividade(){

        try{

            Connection con = ConnectionFactory.createConnectionToMySQL();

            AtividadeDao atividadeDao = new AtividadeDao( con );
            List<Atividade> atividades = atividadeDao.findAll();
            comboModelAtividade.clear();
            comboModelAtividade.addListElements( atividades );
            con.close();

        }catch( SQLException ex ){

            System.out.println( "Erro na conexão do list Turma > ComboBox Atividade" + ex.getMessage() );

        }

    }

    private void updateComboInstrutor(){

        try{

            Connection con = ConnectionFactory.createConnectionToMySQL();

            InstrutorDao instrutorDao = new InstrutorDao( con );
            List<Instrutor> instrutores = instrutorDao.findAll();
            comboModelInstrutor.clear();
            comboModelInstrutor.addListElements( instrutores );
            con.close();

        }catch( SQLException ex ){

            System.out.println( "Erro na conexão do list Turma > ComboBox Atividade" + ex.getMessage() );

        }

    }

    private void fillFieldsByTurma( Turma turma ){

        cbAtividade.setSelectedItem( turma.getAtividade() );
        cbInstrutor.setSelectedItem( turma.getInstrutor() );

        timeHorario.setTime( turma.getHorario() );
        timeDuracao.setTime( turma.getDuracao() );

        dataInicio.getCurrent().setTime( turma.getDataInicio() );
        dataFim.getCurrent().setTime( turma.getDataFim() );
        
        Atividade atividade = comboModelAtividade.getElements().stream()
                .filter( ativ -> ativ.getIdAtividade() == turma.getAtividade().getIdAtividade() )
                .findFirst()
                .get();

        comboModelAtividade.setSelectedItem( atividade );

        Instrutor instrutor = comboModelInstrutor.getElements().stream()
                .filter( instru -> instru.getIdInstrutor() == turma.getInstrutor().getIdInstrutor() )
                .findFirst()
                .get();

        comboModelInstrutor.setSelectedItem( instrutor );

    }

    private void setTurmaByForms( Turma turma ){

        turma.setAtividade( comboModelAtividade.getSelectedItem() );
        turma.setInstrutor( comboModelInstrutor.getSelectedItem() );

        turma.setHorario( timeHorario.getTime() );
        turma.setDuracao( timeDuracao.getTime() );

        turma.setDataInicio( dataInicio.getCurrent().getTime() );
        turma.setDataFim( dataFim.getCurrent().getTime() );

        if( turma.getIdTurma() != -1 ){

            turmaDaoOperate( ( dao ) -> dao.update( turma ) );

        }else{

            turmaDaoOperate( ( dao ) -> dao.create( turma ) );

        }

    }

    private boolean turmaDaoOperate( Function< TurmaDao, Boolean> operation ){

        try{

            Connection con = ConnectionFactory.createConnectionToMySQL();

            TurmaDao turmaDao = new TurmaDao( con );
            return operation.apply( turmaDao );

        }catch( SQLException ex ){

            Logger.getLogger( ViewTurma.class.getName() ).log( Level.SEVERE, null, ex );

        }

        return false;

    }

    private void emptyFields(){

        //!TODO
        dataFim.getCurrent().setTime( new Date() );
        dataInicio.getCurrent().setTime( new Date() );

    }

    private void enableComponents( boolean enable ){

        List<Component> components = Arrays.asList( paneFields.getComponents() );
        components.forEach( c -> c.setEnabled( enable ) );

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PaneRight;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnControleAtividade;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<Atividade> cbAtividade;
    private javax.swing.JComboBox<Instrutor> cbInstrutor;
    private datechooser.beans.DateChooserCombo dataFim;
    private datechooser.beans.DateChooserCombo dataInicio;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNascimento1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JList<Turma> listElements;
    private javax.swing.JPanel paneBorderLayout;
    private javax.swing.JPanel paneControls;
    private javax.swing.JPanel paneFields;
    private javax.swing.JPanel paneLeft;
    private javax.swing.JPanel paneList;
    private javax.swing.JPanel paneTitledContainer;
    private javax.swing.JTextField tfSearch;
    private com.github.lgooddatepicker.components.TimePicker timeDuracao;
    private com.github.lgooddatepicker.components.TimePicker timeHorario;
    // End of variables declaration//GEN-END:variables

}
