/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpr.ads.extendslcc.academia.view.instrutor;

import br.edu.ifpr.ads.extendslcc.academia.bean.Instrutor;
import br.edu.ifpr.ads.extendslcc.academia.bean.Telefone;
import br.edu.ifpr.ads.extendslcc.academia.bean.Titulacao;
import br.edu.ifpr.ads.extendslcc.academia.dao.InstrutorDao;
import br.edu.ifpr.ads.extendslcc.academia.dao.TelefoneDao;
import br.edu.ifpr.ads.extendslcc.academia.dao.TitulacaoDao;
import br.edu.ifpr.ads.extendslcc.academia.util.ConnectionFactory;
import br.edu.ifpr.ads.extendslcc.academia.view.component.FilterListModel;
import br.edu.ifpr.ads.extendslcc.academia.view.component.GenericComboModel;
import br.edu.ifpr.ads.extendslcc.academia.view.component.GenericTypeList;
import java.awt.Component;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.function.Function;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author aluno
 */
public class ViewInstrutor extends javax.swing.JFrame{

    /**
     * Creates new form WindowProprietario
     */
    public ViewInstrutor(){

        initComponents();
        onInit();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneTitledContainer = new javax.swing.JPanel();
        paneBorderLayout = new javax.swing.JPanel();
        paneLeft = new javax.swing.JPanel();
        paneList = new javax.swing.JPanel();
        tfSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listElements = new javax.swing.JList<>();
        lblSearch = new javax.swing.JLabel();
        PaneRight = new javax.swing.JPanel();
        paneFields = new javax.swing.JPanel();
        tfNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblRg = new javax.swing.JLabel();
        tfRg = new javax.swing.JTextField();
        lblTitulacao = new javax.swing.JLabel();
        dateNascimento = new datechooser.beans.DateChooserCombo();
        lblNascimento = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTelefone = new javax.swing.JTable();
        addTelefone = new javax.swing.JButton();
        removeTelefone = new javax.swing.JButton();
        lblTelefone = new javax.swing.JLabel();
        cbTitulacao = new javax.swing.JComboBox<>();
        btnControleTitulacao = new javax.swing.JButton();
        paneControls = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Proprietário");

        paneTitledContainer.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Controle de Instrutor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N

        paneBorderLayout.setLayout(new java.awt.BorderLayout());

        paneLeft.setPreferredSize(new java.awt.Dimension(455, 367));

        paneList.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Lista de Instrutores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jScrollPane1.setViewportView(listElements);

        lblSearch.setText("Pesquisar:");

        javax.swing.GroupLayout paneListLayout = new javax.swing.GroupLayout(paneList);
        paneList.setLayout(paneListLayout);
        paneListLayout.setHorizontalGroup(
            paneListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(paneListLayout.createSequentialGroup()
                        .addComponent(lblSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneListLayout.setVerticalGroup(
            paneListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneListLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(paneListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout paneLeftLayout = new javax.swing.GroupLayout(paneLeft);
        paneLeft.setLayout(paneLeftLayout);
        paneLeftLayout.setHorizontalGroup(
            paneLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneLeftLayout.createSequentialGroup()
                .addComponent(paneList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneLeftLayout.setVerticalGroup(
            paneLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLeftLayout.createSequentialGroup()
                .addComponent(paneList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        paneBorderLayout.add(paneLeft, java.awt.BorderLayout.CENTER);

        PaneRight.setPreferredSize(new java.awt.Dimension(600, 367));

        paneFields.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Instrutor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        lblNome.setText("Nome:");

        lblRg.setText("RG:");

        lblTitulacao.setText("Titulação:");

        lblNascimento.setText("Data de Nascimento");

        tbTelefone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbTelefone);

        addTelefone.setText("+");
        addTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTelefoneActionPerformed(evt);
            }
        });

        removeTelefone.setText("-");
        removeTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTelefoneActionPerformed(evt);
            }
        });

        lblTelefone.setText("Telefone:");

        btnControleTitulacao.setText("...");
        btnControleTitulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControleTitulacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneFieldsLayout = new javax.swing.GroupLayout(paneFields);
        paneFields.setLayout(paneFieldsLayout);
        paneFieldsLayout.setHorizontalGroup(
            paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneFieldsLayout.createSequentialGroup()
                .addGroup(paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneFieldsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRg, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneFieldsLayout.createSequentialGroup()
                        .addGap(0, 52, Short.MAX_VALUE)
                        .addGroup(paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulacao, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTelefone, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneFieldsLayout.createSequentialGroup()
                        .addComponent(tfRg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addGroup(paneFieldsLayout.createSequentialGroup()
                        .addGroup(paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(cbTitulacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnControleTitulacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addContainerGap())
        );
        paneFieldsLayout.setVerticalGroup(
            paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneFieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblNascimento)
                        .addComponent(dateNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulacao)
                    .addComponent(cbTitulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnControleTitulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneFieldsLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(addTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeTelefone))
                    .addGroup(paneFieldsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(paneFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefone))))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PaneRightLayout = new javax.swing.GroupLayout(PaneRight);
        PaneRight.setLayout(PaneRightLayout);
        PaneRightLayout.setHorizontalGroup(
            PaneRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PaneRightLayout.setVerticalGroup(
            PaneRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneRightLayout.createSequentialGroup()
                .addComponent(paneFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        paneBorderLayout.add(PaneRight, java.awt.BorderLayout.LINE_END);

        paneControls.setPreferredSize(new java.awt.Dimension(948, 45));

        btnNew.setText("Cadastrar");
        btnNew.setPreferredSize(new java.awt.Dimension(90, 35));
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        paneControls.add(btnNew);

        btnUpdate.setText("Alterar");
        btnUpdate.setEnabled(false);
        btnUpdate.setPreferredSize(new java.awt.Dimension(90, 35));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        paneControls.add(btnUpdate);

        btnDelete.setText("Excluir");
        btnDelete.setEnabled(false);
        btnDelete.setPreferredSize(new java.awt.Dimension(90, 35));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        paneControls.add(btnDelete);

        btnCancel.setText("Cancelar");
        btnCancel.setEnabled(false);
        btnCancel.setPreferredSize(new java.awt.Dimension(90, 35));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        paneControls.add(btnCancel);

        paneBorderLayout.add(paneControls, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout paneTitledContainerLayout = new javax.swing.GroupLayout(paneTitledContainer);
        paneTitledContainer.setLayout(paneTitledContainerLayout);
        paneTitledContainerLayout.setHorizontalGroup(
            paneTitledContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTitledContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBorderLayout, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneTitledContainerLayout.setVerticalGroup(
            paneTitledContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTitledContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBorderLayout, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneTitledContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneTitledContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private GenericComboModel<Titulacao> comboTitulacaoModel;
    private FilterListModel<Instrutor> listElemetsModel;
    private TelefoneTableModel telefoneTableModel;
    private Instrutor currentInstrutor;

    private void onInit(){

        enableComponents( false );
        Connection con;

        try{

            con = ConnectionFactory.createConnectionToMySQL();
            InstrutorDao instrutorDao = new InstrutorDao( con );
            listElemetsModel = new FilterListModel<Instrutor>( instrutorDao.findAll() );
            listElements.setModel( listElemetsModel );
            con.close();

        }catch( SQLException ex ){

            System.out.println( "Erro na conexão do list Instrutor " + ex.getMessage() );

        }

        comboTitulacaoModel = new GenericComboModel<>();
        cbTitulacao.setModel( comboTitulacaoModel );
        updateComboTitulacao();

        telefoneTableModel = new TelefoneTableModel( tbTelefone );
        tbTelefone.setModel( telefoneTableModel );
        tbTelefone.getColumnModel().getColumn( 1 ).setCellEditor( new ComboTipoTelefone() );

        tfSearch.getDocument().addDocumentListener( new DocumentListener(){
            @Override
            public void insertUpdate( DocumentEvent e ){
                filter();
            }

            @Override
            public void removeUpdate( DocumentEvent e ){
                filter();
            }

            @Override
            public void changedUpdate( DocumentEvent e ){
                filter();
            }

            private void filter(){

                listElemetsModel.filter( tfSearch.getText() );

            }

        } );

        listElements.getSelectionModel().addListSelectionListener( new ListSelectionListener(){//seleção alterada

            @Override
            public void valueChanged( ListSelectionEvent e ){

                if( !e.getValueIsAdjusting() ){

                    if( listElements.getSelectedIndex() >= 0 ){

                        ViewInstrutor.this.currentInstrutor = listElements.getSelectedValue();
                        fillFieldsByInstrutor( ViewInstrutor.this.currentInstrutor );
                        System.out.println( currentInstrutor.getTelefones() );
                        btnUpdate.setEnabled( true );
                        btnDelete.setEnabled( true );

                    }else{

                        enableComponents( false );
                        btnUpdate.setEnabled( false );
                        btnDelete.setEnabled( false );

                    }

                }

            }

        } );

    }

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed

        this.emptyFields();
        this.currentInstrutor = new Instrutor();
        listElements.clearSelection();
        listElements.setEnabled( false );
        btnNew.setEnabled( false );
        btnDelete.setEnabled( false );
        btnCancel.setEnabled( true );
        btnUpdate.setEnabled( true );
        btnUpdate.setText( "Salvar" );
        enableComponents( true );
        this.delTelefone.clear();

    }//GEN-LAST:event_btnNewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        if( btnNew.isEnabled() ){

            System.out.println( "Editar" );
            listElements.setEnabled( false );
            btnDelete.setEnabled( false );
            btnNew.setEnabled( false );
            btnUpdate.setText( "Salvar" );
            btnCancel.setEnabled( true );
            enableComponents( true );
//            this.cadTelefone.clear();
            this.delTelefone.clear();
            btnUpdate.setEnabled( true );

        }else{// EXECUTE SALVAR

            if( cbTitulacao.getSelectedIndex() == -1 ){

                JOptionPane.showMessageDialog( this, "Seleciona uma titualção", "Erro", JOptionPane.ERROR_MESSAGE );
                return;

            }

            System.out.println( "Salvar" );
            listElements.setEnabled( true );
            btnNew.setEnabled( true );
            btnUpdate.setText( "Editar" );
            btnCancel.setEnabled( false );
            enableComponents( false );
            this.setInstrutorByForms( this.currentInstrutor );

            if( !listElemetsModel.contains( currentInstrutor ) ){

                listElemetsModel.addElement( currentInstrutor );

            }

            listElements.setSelectedValue( this.currentInstrutor, true );

        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        Instrutor instrutor = listElements.getSelectedValue();
        listElements.clearSelection();
        listElemetsModel.removeElement( instrutor );
        btnDelete.setEnabled( false );
        instrutorDaoOperate( ( dao ) -> dao.delete( instrutor ) );

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        listElements.setEnabled( true );
        btnNew.setEnabled( true );
        btnUpdate.setText( "Editar" );
        btnCancel.setEnabled( false );
        btnDelete.setEnabled( listElements.getSelectedValue() != null );
        enableComponents( false );

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnControleTitulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControleTitulacaoActionPerformed

        try{

            Connection con = ConnectionFactory.createConnectionToMySQL();
            GenericTypeList< Titulacao, TitulacaoDao> titulacaoList = new GenericTypeList<>( "Titulação", Titulacao::new, () -> new TitulacaoDao( con ) );

            titulacaoList.setModal( true );
            titulacaoList.setLocationRelativeTo( this );
            titulacaoList.setVisible( true );
            updateComboTitulacao();

        }catch( SQLException ex ){
            Logger.getLogger( ViewInstrutor.class.getName() ).log( Level.SEVERE, null, ex );
        }


    }//GEN-LAST:event_btnControleTitulacaoActionPerformed

    private void updateComboTitulacao(){

        try{

            Connection con = ConnectionFactory.createConnectionToMySQL();

            TitulacaoDao titulacaoDao = new TitulacaoDao( con );
            List<Titulacao> titulacoes = titulacaoDao.findAll();
            comboTitulacaoModel.clear();
            comboTitulacaoModel.addListElements( titulacoes );
            con.close();

        }catch( SQLException ex ){

            System.out.println( "Erro na conexão do list Instrutor > ComboBox Titulação" + ex.getMessage() );

        }

    }

    private void fillFieldsByInstrutor( Instrutor instrutor ){

        tfNome.setText( instrutor.getNome() );
        tfRg.setText( instrutor.getRg() );
        dateNascimento.getCurrent().setTime( instrutor.getNascimento() );
        tfNome.setText( instrutor.getNome() );
        for( Titulacao element : comboTitulacaoModel.getElements() ){

            System.out.println( element );
            System.out.println( element.getIdTitulacao() );

        }
        System.out.println( instrutor.getTitulacao() );
        System.out.println( instrutor.getTitulacao().getIdTitulacao() );
        Titulacao titulacao = comboTitulacaoModel.getElements().stream()
                .filter( t -> t.getIdTitulacao() == instrutor.getTitulacao().getIdTitulacao() )
                .findFirst()
                .get();

        comboTitulacaoModel.setSelectedItem( titulacao );

        telefoneTableModel.clear();
        telefoneTableModel.addAll( instrutor.getTelefones() );

    }

    private void setInstrutorByForms( Instrutor instrutor ){

        instrutor.setNome( tfNome.getText() );
        instrutor.setRg( tfRg.getText() );
        instrutor.setNascimento( dateNascimento.getCurrent().getTime() );
        instrutor.setTitulacao( comboTitulacaoModel.getSelectedItem() );

        try{

            Connection con = ConnectionFactory.createConnectionToMySQL();
            TelefoneDao telefoneDao = new TelefoneDao( con );
            delTelefone.stream()
                    .filter( t -> t.getIdTelefone() != -1 )
                    .forEach( t -> telefoneDao.delete( t ) );
            con.close();

        }catch( SQLException ex ){

            Logger.getLogger( ViewInstrutor.class.getName() ).log( Level.SEVERE, null, ex );

        }

        if( instrutor.getIdInstrutor() != -1 ){

            instrutorDaoOperate( ( dao ) -> dao.update( instrutor ) );

        }else{

            instrutorDaoOperate( ( dao ) -> dao.create( instrutor ) );

        }

    }

    private boolean instrutorDaoOperate( Function< InstrutorDao, Boolean> operation ){

        try{

            Connection con = ConnectionFactory.createConnectionToMySQL();

            InstrutorDao instrutorDao = new InstrutorDao( con );
            return operation.apply( instrutorDao );

        }catch( SQLException ex ){

            Logger.getLogger( ViewInstrutor.class.getName() ).log( Level.SEVERE, null, ex );

        }

        return false;

    }

    private void emptyFields(){

        tfNome.setText( "" );
        tfRg.setText( "" );
        dateNascimento.getCurrent().setTime( new Date() );
        telefoneTableModel.clear();

    }

    private void enableComponents( boolean enable ){

        tbTelefone.setEnabled( enable );
        List<Component> components = Arrays.asList( paneFields.getComponents() );
        components.forEach( c -> c.setEnabled( enable ) );

    }

//    List<Telefone> cadTelefone = new LinkedList<>();;
    List<Telefone> delTelefone = new LinkedList<>();

    private void addTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTelefoneActionPerformed

        Telefone telefone = new Telefone( "", Telefone.TIPOS_TELEFONE[0], this.currentInstrutor );
        telefoneTableModel.addRow( telefone );
        this.currentInstrutor.addTelefone( telefone );

    }//GEN-LAST:event_addTelefoneActionPerformed

    private void removeTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTelefoneActionPerformed

        int selectedRow = tbTelefone.getSelectedRow();

        if( selectedRow != -1 ){

            Telefone telefone = telefoneTableModel.getTelefone( selectedRow );
            delTelefone.add( telefone );
            telefoneTableModel.removeTelefone( telefone );
            currentInstrutor.removeTelefone( telefone );

        }

    }//GEN-LAST:event_removeTelefoneActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PaneRight;
    private javax.swing.JButton addTelefone;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnControleTitulacao;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<Titulacao> cbTitulacao;
    private datechooser.beans.DateChooserCombo dateNascimento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTitulacao;
    private javax.swing.JList<Instrutor> listElements;
    private javax.swing.JPanel paneBorderLayout;
    private javax.swing.JPanel paneControls;
    private javax.swing.JPanel paneFields;
    private javax.swing.JPanel paneLeft;
    private javax.swing.JPanel paneList;
    private javax.swing.JPanel paneTitledContainer;
    private javax.swing.JButton removeTelefone;
    private javax.swing.JTable tbTelefone;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfRg;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
