/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpr.ads.extendslcc.academia.view.component;

import br.edu.ifpr.ads.extendslcc.academia.bean.Type;
import br.edu.ifpr.ads.extendslcc.academia.dao.Dao;
import java.util.List;
import java.util.function.Supplier;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author aluno
 */
public class GenericTypeList< T extends Type, D extends Dao> extends JDialog{

    /**
     * Creates new form GenericTypeList
     */
    public GenericTypeList( String title, Supplier<T> typeSupplier, Supplier<D> daoSupplier ){
        initComponents();

        setTitle( title );
        this.title = title;
        this.daoSupplier = daoSupplier;
        this.typeSupplier = typeSupplier;
        onInit();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        elementList = new javax.swing.JList<>();
        btnCad = new javax.swing.JToggleButton();
        btnUpdate = new javax.swing.JToggleButton();
        btnDelete = new javax.swing.JToggleButton();

        setMaximumSize(new java.awt.Dimension(346, 290));
        setMinimumSize(new java.awt.Dimension(346, 290));

        elementList.setToolTipText("");
        jScrollPane1.setViewportView(elementList);

        btnCad.setText("Cadastrar");
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });

        btnUpdate.setText("Alterar");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Excluir");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private final String title;
    private Supplier<D> daoSupplier;
    private Supplier<T> typeSupplier;

    public D generateDao(){

        return daoSupplier.get();

    }

    public T generatetype(){

        return typeSupplier.get();

    }

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        if( elementList.getSelectedValue() != null ){

            String nome = JOptionPane.showInputDialog( this, "Insira o novo nome de " + title + " de " + elementList.getSelectedValue().getNome(), elementList.getSelectedValue().getNome() );

            if( nome == null ){
                return;
            }

            D dao = generateDao();
            T type = elementList.getSelectedValue();
            System.out.println( type );
            System.out.println( "id: " + type.getId() );
            type.setNome( nome );
            dao.update( type );

            int lastIndex = type.getId();
            JOptionPane.showMessageDialog( this, title + " \"" + nome + "\" alterado com sucesso!" );

        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed

        String nome = JOptionPane.showInputDialog( this, "Cadastrar " + title );

        if( nome == null ){
            return;
        }

        D dao = generateDao();
        T type = generatetype();
        type.setNome( nome );
        dao.create( type );

        JOptionPane.showMessageDialog( this, title + " \"" + nome + "\" cadastrado com sucesso!" );
        listModel.addElement( type );
        elementList.setSelectedValue( type, true );

    }//GEN-LAST:event_btnCadActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        if( JOptionPane.showConfirmDialog( this, "Confirmar exclusão de " + title + ": "
                + elementList.getSelectedValue().getNome(), "", JOptionPane.YES_NO_OPTION ) == JOptionPane.YES_OPTION ){

            D dao = generateDao();
            T type = elementList.getSelectedValue();
            
            if( dao.delete( type ) ){
                
                JOptionPane.showMessageDialog( this, title + " \"" + type.getNome() + "\" excluido com sucesso!" );
                
            }else{
                
                JOptionPane.showMessageDialog( this, title + " \"" +  type.getNome() + "\" não pode ser deletado pois é referenciado por outro Item." );
                
            }

        }

    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCad;
    private javax.swing.JToggleButton btnDelete;
    private javax.swing.JToggleButton btnUpdate;
    private javax.swing.JList<T> elementList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private DefaultListModel<T> listModel = new DefaultListModel<>();

    private void onInit(){

        updateItens();
        elementList.setModel( listModel );
        elementList.setSelectionMode( ListSelectionModel.SINGLE_SELECTION );

        elementList.getSelectionModel().addListSelectionListener( new ListSelectionListener(){

            @Override
            public void valueChanged( ListSelectionEvent arg0 ){

                if( elementList.getSelectedIndex() == -1 ){

                    btnUpdate.setEnabled( false );
                    btnDelete.setEnabled( false );

                }else{

                    btnUpdate.setEnabled( true );
                    btnDelete.setEnabled( true );

                }
            }

        } );
        
    }

    private void updateItens(){

        listModel.removeAllElements();

        D dao = generateDao();
        List<T> listTypes = dao.findAll();
        listTypes.forEach( type -> listModel.addElement( type ) );
        
    }

    public T getSelectedType(){

        return elementList.getSelectedValue();

    }

}
