/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpr.ads.extendslcc.academia.view;

/**
 *
 * @author LucasLCC
 */
public class MainWindowOLD extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindowOLD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    /*
    *   Janelas
    */
    
    public void onInit(){
    
        //DaoFactory.createConnection();
    
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        itemProprietario = new javax.swing.JMenuItem();
        itemCategoria = new javax.swing.JMenuItem();
        itemMarca = new javax.swing.JMenuItem();
        itemVeiculo = new javax.swing.JMenuItem();
        itemMunicipio = new javax.swing.JMenuItem();
        itemEstado = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 51, 51));

        menuCadastro.setText("Cadastros");

        itemProprietario.setText("Proprietário");
        itemProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProprietarioActionPerformed(evt);
            }
        });
        menuCadastro.add(itemProprietario);

        itemCategoria.setText("Categoria");
        itemCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCategoriaActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCategoria);

        itemMarca.setText("Marca");
        itemMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMarcaActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMarca);

        itemVeiculo.setText("Veículo");
        itemVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVeiculoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemVeiculo);

        itemMunicipio.setText("Município");
        itemMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMunicipioActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMunicipio);

        itemEstado.setText("Estado");
        itemEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEstadoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemEstado);

        jMenuBar1.add(menuCadastro);

        jMenu2.setText("Listas");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProprietarioActionPerformed
        
        WindowManagerOld.openWindowProprietario();
        
    }//GEN-LAST:event_itemProprietarioActionPerformed

    private void itemCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCategoriaActionPerformed

        WindowManagerOld.openWindowCategoria();

    }//GEN-LAST:event_itemCategoriaActionPerformed

    private void itemVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVeiculoActionPerformed

        WindowManagerOld.openWindowVeiculo();
        
    }//GEN-LAST:event_itemVeiculoActionPerformed

    private void itemMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMunicipioActionPerformed

        WindowManagerOld.openWindowCidade();

    }//GEN-LAST:event_itemMunicipioActionPerformed

    private void itemEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEstadoActionPerformed

        WindowManagerOld.openWindowEstado();

    }//GEN-LAST:event_itemEstadoActionPerformed

    private void itemMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMarcaActionPerformed
        
        WindowManagerOld.openWindowMarca();
        
    }//GEN-LAST:event_itemMarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindowOLD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindowOLD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindowOLD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindowOLD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindowOLD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCategoria;
    private javax.swing.JMenuItem itemEstado;
    private javax.swing.JMenuItem itemMarca;
    private javax.swing.JMenuItem itemMunicipio;
    private javax.swing.JMenuItem itemProprietario;
    private javax.swing.JMenuItem itemVeiculo;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCadastro;
    // End of variables declaration//GEN-END:variables
}
