/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpr.ads.extendslcc.academia.view;

import br.ifpr.edu.adslcc.util.DaoFactory;
import com.github.lgooddatepicker.components.DatePicker;
import datechooser.beans.DateChooserCombo;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author aluno
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    /*
    *   Janelas
    */
    
    public void onInit(){
    
        DaoFactory.createConnection();
    
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        timePicker1 = new com.github.lgooddatepicker.components.TimePicker();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        itemInstrutor = new javax.swing.JMenuItem();
        itemTurma = new javax.swing.JMenuItem();
        itemAtividade = new javax.swing.JMenuItem();
        itemAluno = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        itemMatricula = new javax.swing.JMenuItem();
        itemChamada = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Academia de Ginástica");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        menuCadastro.setText("Cadastros");

        itemInstrutor.setText("Instrutor");
        itemInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInstrutorActionPerformed(evt);
            }
        });
        menuCadastro.add(itemInstrutor);

        itemTurma.setText("Turma");
        itemTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTurmaActionPerformed(evt);
            }
        });
        menuCadastro.add(itemTurma);

        itemAtividade.setText("Atividade");
        itemAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAtividadeActionPerformed(evt);
            }
        });
        menuCadastro.add(itemAtividade);

        itemAluno.setText("Aluno");
        itemAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAlunoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemAluno);

        jMenuBar1.add(menuCadastro);

        jMenu2.setText("Listas");
        jMenuBar1.add(jMenu2);

        jMenu1.setText("Controles");

        itemMatricula.setText("Matricula");
        jMenu1.add(itemMatricula);

        itemChamada.setText("Chamada");
        itemChamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemChamadaActionPerformed(evt);
            }
        });
        jMenu1.add(itemChamada);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(timePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 126, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)))
                .addComponent(timePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInstrutorActionPerformed
        
        WindowManager.openWindowProprietario();
        
    }//GEN-LAST:event_itemInstrutorActionPerformed

    private void itemTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTurmaActionPerformed

        WindowManager.openWindowCategoria();

    }//GEN-LAST:event_itemTurmaActionPerformed

    private void itemAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAlunoActionPerformed

        WindowManager.openWindowVeiculo();
        
    }//GEN-LAST:event_itemAlunoActionPerformed

    private void itemAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAtividadeActionPerformed
        
        WindowManager.openWindowMarca();
        
    }//GEN-LAST:event_itemAtividadeActionPerformed

    private void itemChamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemChamadaActionPerformed
        // TODO add your handling code here:
        //Date date = Date.from( datePicker1.getDate().  );
        DatePicker datePicker = new DatePicker();
        datePicker.setDate( LocalDate.parse( "2018-10-20" ) );
        datePicker1.setText( "2018-10-20" );
        //datePicker.setDate( LocalDate. );
        System.out.println( dateChooserCombo1.getCurrent().getTime());
        java.util.Date date = java.sql.Date.valueOf(datePicker.getDate());
        System.out.println( date );
        
        
    }//GEN-LAST:event_itemChamadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JMenuItem itemAluno;
    private javax.swing.JMenuItem itemAtividade;
    private javax.swing.JMenuItem itemChamada;
    private javax.swing.JMenuItem itemInstrutor;
    private javax.swing.JMenuItem itemMatricula;
    private javax.swing.JMenuItem itemTurma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCadastro;
    private com.github.lgooddatepicker.components.TimePicker timePicker1;
    // End of variables declaration//GEN-END:variables
}
